version: '3.8'
services:
  neo4j:
    container_name: neo4j
    image: neo4j:5.22.0-community
    environment:
      NEO4J_AUTH: ${NEO4J_USER}/${NEO4J_PASSWORD}
      NEO4J_PLUGINS: '["graph-data-science", "apoc"]'
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_apoc_export_file_enabled: 'true'
      NEO4J_apoc_import_file_enabled: 'true'
      NEO4J_apoc_import_file_use__neo4j__config: 'true'
      NEO4J_dbms_security_procedures_unrestricted: 'gds.*,apoc.*'
    ports:
      - "127.0.0.1:7474:7474"
      - "127.0.0.1:7687:7687"
    volumes:
      - neo4j:/var/lib/neo4j # Persist all Neo4j data
    healthcheck:
      test: ["CMD", "neo4j-admin", "server", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - graphdb-network
  
  graphdb-ingest:
    build:
      context: ./src
      dockerfile: Dockerfile
    environment:
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: ${NEO4J_USER}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD}
    container_name: graphdb-ingest
    restart: on-failure:5
    depends_on:
      neo4j:
        condition: service_healthy
    command: sh -c "until nc -z neo4j 7687; do echo 'Waiting for Neo4j...'; sleep 2; done; sh /app/graph_ingest/ingest.sh"
    networks:
      - graphdb-network
    volumes:
      - graph_ingest_data:/app:Z
    deploy:
      replicas: ${ENABLE_INGEST:-1} # Default is 1, but set to 0 to disable

volumes:
  neo4j:
    driver: local
  graph_ingest_data:
    driver: local

networks:
  graphdb-network:
    driver: bridge